name: Protected folder guards

on:
  [create, pull_request]:
    branches: [ main ]
    paths:
    - 'internal/server/**'

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
    - name: Warning
      uses: mb2dev/github-action-comment-pull-request@1.0.0
      with:
        message: "# ⚠️⚠️ Warning! This diff contains changes in protected folders. ⚠️ ⚠️"
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
